client.secret=1d0detpv29n5s1ph7oatecb34o1sn9g1t9u20fnekadgfk9i2teo
client.id=288rit08j40dheeko3sm6am77g
oauthURL=https://us-east-24on0hmtxf.auth.us-east-2.amazoncognito.com/oauth2/token
loginURL=https://us-east-24on0hmtxf.auth.us-east-2.amazoncognito.com/login
redirectURL=http://localhost:8080/TravelJournal_war/auth
region=us-east-2
poolId=us-east-2_4on0HMTXF